/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/week` | `/week`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboardSteps`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/main/adjustWeek`; params?: Router.UnknownInputParams; } | { pathname: `/main/loggedout`; params?: Router.UnknownInputParams; } | { pathname: `/main/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/main/recipeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/main/week`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/week` | `/week`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/onboardSteps`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/main/adjustWeek`; params?: Router.UnknownOutputParams; } | { pathname: `/main/loggedout`; params?: Router.UnknownOutputParams; } | { pathname: `/main/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/main/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/main/recipeDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/main/week`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/list${`?${string}` | `#${string}` | ''}` | `/list${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/week${`?${string}` | `#${string}` | ''}` | `/week${`?${string}` | `#${string}` | ''}` | `/auth/onboardSteps${`?${string}` | `#${string}` | ''}` | `/auth/onboarding${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/main/adjustWeek${`?${string}` | `#${string}` | ''}` | `/main/loggedout${`?${string}` | `#${string}` | ''}` | `/main/paywall${`?${string}` | `#${string}` | ''}` | `/main/profile${`?${string}` | `#${string}` | ''}` | `/main/recipeDetail${`?${string}` | `#${string}` | ''}` | `/main/week${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/week` | `/week`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboardSteps`; params?: Router.UnknownInputParams; } | { pathname: `/auth/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/main/adjustWeek`; params?: Router.UnknownInputParams; } | { pathname: `/main/loggedout`; params?: Router.UnknownInputParams; } | { pathname: `/main/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/main/recipeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/main/week`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
